# Generated by Django 4.2 on 2024-08-08 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='الاسم*')),
                ('description', models.TextField(max_length=500, verbose_name='الوصف')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الاسئلة*')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='الوصف')),
                ('url', models.URLField(blank=True, max_length=5000, null=True, verbose_name='اضافة رابط التسجيل')),
                ('audio_file1', models.FileField(blank=True, null=True, upload_to='recordings/')),
                ('audio_file2', models.FileField(blank=True, null=True, upload_to='recordings/')),
                ('audio_file3', models.FileField(blank=True, null=True, upload_to='recordings/')),
                ('audio_file4', models.FileField(blank=True, null=True, upload_to='recordings/')),
                ('audio_file5', models.FileField(blank=True, null=True, upload_to='recordings/')),
                ('date', models.DateField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الاسئلة*')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question/img', verbose_name='اضافة صورة الاسئلة')),
                ('file', models.FileField(blank=True, null=True, upload_to='question/pdf', verbose_name='او اضافة pdf الاسئلة')),
                ('url', models.URLField(blank=True, max_length=5000, null=True, verbose_name='او اضافة رابط الاسئلة')),
                ('date', models.DateField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='اسم الملزمة*')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='الوصف')),
                ('file', models.FileField(blank=True, null=True, upload_to='notebooks/', verbose_name='الملزمة')),
                ('url', models.URLField(blank=True, max_length=5000, null=True, verbose_name='او اضافة رابط الملزمة')),
                ('date', models.DateField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mlkhasat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الملخص*')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mlkhasat/img', verbose_name='اضافة صورة الملخص')),
                ('file', models.FileField(blank=True, null=True, upload_to='mlkhasat/pdf', verbose_name='او اضافة pdf المخلص')),
                ('url', models.URLField(blank=True, max_length=5000, null=True, verbose_name='او اضافة رابط الملخص')),
                ('date', models.DateField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportantQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الاسئلة*')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question/img', verbose_name='اضافة صورة الاسئلة')),
                ('file', models.FileField(blank=True, null=True, upload_to='question/pdf', verbose_name='او اضافة pdf الاسئلة')),
                ('url', models.URLField(blank=True, max_length=5000, null=True, verbose_name='او اضافة رابط الاسئلة')),
                ('date', models.DateField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='اسم الكتاب*')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='الوصف')),
                ('file', models.FileField(blank=True, null=True, upload_to='books/', verbose_name='الكتاب')),
                ('url', models.URLField(blank=True, max_length=5000, null=True, verbose_name='او اضافة رابط الكتاب')),
                ('date', models.DateField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
